-- Migration 15: Seeds LinkedIn sectors + geos
-- Generated from prompt spec seed (136 sectors, all verified)

-- Sectors (136)
INSERT INTO linkedin_sectors (id, label_fr, parent_category, verified) VALUES
  (122, 'Services relatifs aux bâtiments', 'Administrative and Support Services', true),
  (110, 'Événementiel', 'Administrative and Support Services', true),
  (48, 'Construction', 'Construction', true),
  (406, 'Construction de bâtiments', 'Construction', true),
  (413, 'Construction de bâtiments non résidentiels', 'Construction', true),
  (408, 'Construction de bâtiments résidentiels', 'Construction', true),
  (431, 'Construction de routes, autoroutes et ponts', 'Construction', true),
  (419, 'Construction des services publics de distribution', 'Construction', true),
  (51, 'Génie civil', 'Construction', true),
  (1001, 'Travaux Publics', 'Construction', true),
  (453, 'Travaux d''installation électrique, plomberie et autres travaux d''installation', 'Construction', true),
  (435, 'Travaux de construction spécialisés', 'Construction', true),
  (460, 'Travaux de finition de bâtiment', 'Construction', true),
  (436, 'Travaux de maçonnerie générale et gros œuvre de bâtiment', 'Construction', true),
  (3192, 'Biens de consommation', 'Consumer Services', true),
  (132, 'Fournisseurs d''apprentissage en ligne', 'Education', true),
  (63, 'Agriculture', 'Farming, Ranching, Forestry', true),
  (141, 'Commerce et développement international', 'Financial Services', true),
  (388, 'Programmes de qualité environnementale', 'Government Administration', true),
  (2081, 'Hôpitaux', 'Hospitals and Health Care', true),
  (14, 'Hôpitaux et services de santé', 'Hospitals and Health Care', true),
  (3225, 'Articles de sport', 'Manufacturing', true),
  (3226, 'Aéronautique et aérospatiale', 'Manufacturing', true),
  (679, 'Cokéfaction et raffinage', 'Manufacturing', true),
  (62, 'Construction de matériel ferroviaire', 'Manufacturing', true),
  (1002, 'Distribution de Pièces', 'Manufacturing', true),
  (3223, 'Emballages et conteneurs', 'Manufacturing', true),
  (615, 'Fabrication d''accessoires de mode', 'Manufacturing', true),
  (481, 'Fabrication d''aliments pour animaux', 'Manufacturing', true),
  (998, 'Fabrication d''appareils d''éclairage électrique', 'Manufacturing', true),
  (1005, 'Fabrication d''appareils électroménagers', 'Manufacturing', true),
  (112, 'Fabrication d''appareils électroménagers, électriques et électroniques', 'Manufacturing', true),
  (20, 'Fabrication d''articles de sport', 'Manufacturing', true),
  (146, 'Fabrication d''emballages et conteneurs', 'Manufacturing', true),
  (983, 'Fabrication d''instruments de mesure et de contrôle', 'Manufacturing', true),
  (852, 'Fabrication d''éléments en métal pour la construction', 'Manufacturing', true),
  (973, 'Fabrication d''équipements audio et vidéo', 'Manufacturing', true),
  (923, 'Fabrication d''équipements aérauliques et frigorifiques', 'Manufacturing', true),
  (964, 'Fabrication d''équipements de communication', 'Manufacturing', true),
  (17, 'Fabrication d''équipements médicaux', 'Manufacturing', true),
  (3241, 'Fabrication d''équipements pour les énergies renouvelables', 'Manufacturing', true),
  (2468, 'Fabrication d''équipements électriques', 'Manufacturing', true),
  (562, 'Fabrication de bière', 'Manufacturing', true),
  (142, 'Fabrication de boissons', 'Manufacturing', true),
  (703, 'Fabrication de caoutchouc et fibres synthétiques', 'Manufacturing', true),
  (794, 'Fabrication de chaux et d''éléments en plâtre', 'Manufacturing', true),
  (52, 'Fabrication de composants pour l''industrie aéronautique et aérospatiale', 'Manufacturing', true),
  (3254, 'Fabrication de compteurs intelligents', 'Manufacturing', true),
  (849, 'Fabrication de coutellerie et d''outils à main', 'Manufacturing', true),
  (55, 'Fabrication de machines', 'Manufacturing', true),
  (901, 'Fabrication de machines agricoles et forestières, pour l''extraction ou la construction', 'Manufacturing', true),
  (147, 'Fabrication de machines d''automatisation', 'Manufacturing', true),
  (135, 'Fabrication de machines industrielles', 'Manufacturing', true),
  (928, 'Fabrication de machines pour la métallurgie', 'Manufacturing', true),
  (918, 'Fabrication de machines pour le commerce et les industries de services', 'Manufacturing', true),
  (1095, 'Fabrication de matelas et stores', 'Manufacturing', true),
  (1029, 'Fabrication de matériel de transport', 'Manufacturing', true),
  (1090, 'Fabrication de meubles de bureau et de magasin', 'Manufacturing', true),
  (26, 'Fabrication de meubles et d''articles d''ameublement', 'Manufacturing', true),
  (1080, 'Fabrication de meubles pour particuliers et institutions', 'Manufacturing', true),
  (935, 'Fabrication de moteurs, génératrices et transformateurs électriques et de matériel de distribution et de commande électrique', 'Manufacturing', true),
  (61, 'Fabrication de papier et de produits en papier', 'Manufacturing', true),
  (722, 'Fabrication de peintures, enduits et adhésifs', 'Manufacturing', true),
  (3255, 'Fabrication de piles à combustible', 'Manufacturing', true),
  (876, 'Fabrication de pièces tournées et d''éléments de fixation', 'Manufacturing', true),
  (799, 'Fabrication de produits abrasifs et de produits minéraux non métalliques', 'Manufacturing', true),
  (709, 'Fabrication de produits agrochimiques et d''engrais', 'Manufacturing', true),
  (23, 'Fabrication de produits alimentaires et boissons', 'Manufacturing', true),
  (54, 'Fabrication de produits chimiques', 'Manufacturing', true),
  (773, 'Fabrication de produits en argile et matériaux réfractaires', 'Manufacturing', true),
  (784, 'Fabrication de produits en bois', 'Manufacturing', true),
  (763, 'Fabrication de produits en caoutchouc', 'Manufacturing', true),
  (743, 'Fabrication de produits en caoutchouc et en plastique', 'Manufacturing', true),
  (117, 'Fabrication de produits en plastique', 'Manufacturing', true),
  (24, 'Fabrication de produits informatiques et électroniques', 'Manufacturing', true),
  (840, 'Fabrication de produits métalliques', 'Manufacturing', true),
  (873, 'Fabrication de ressorts et de produits en fil métallique', 'Manufacturing', true),
  (3247, 'Fabrication de robots', 'Manufacturing', true),
  (861, 'Fabrication de réservoirs, citernes et conteneurs métalliques', 'Manufacturing', true),
  (727, 'Fabrication de savons, détergents et produits d''entretien', 'Manufacturing', true),
  (7, 'Fabrication de semi-conducteurs', 'Manufacturing', true),
  (144, 'Fabrication de semi-conducteurs pour énergies renouvelables', 'Manufacturing', true),
  (871, 'Fabrication de serrures et de ferrures', 'Manufacturing', true),
  (994, 'Fabrication de supports magnétiques et optiques', 'Manufacturing', true),
  (60, 'Fabrication de textiles', 'Manufacturing', true),
  (887, 'Fabrication de valves, billes et cylindres en métal', 'Manufacturing', true),
  (779, 'Fabrication de verre et d''articles en verre', 'Manufacturing', true),
  (145, 'Fabrication de verre, de produits céramiques et de ciment', 'Manufacturing', true),
  (1, 'Fabrication pour l''aérospatiale et la défense', 'Manufacturing', true),
  (3198, 'Industrie automobile', 'Manufacturing', true),
  (3239, 'Industrie bois et papiers', 'Manufacturing', true),
  (25, 'Industrie manufacturière', 'Manufacturing', true),
  (3193, 'Meubles', 'Manufacturing', true),
  (807, 'Métallurgie', 'Manufacturing', true),
  (3218, 'Semi-conducteurs', 'Manufacturing', true),
  (83, 'Services d''impression', 'Manufacturing', true),
  (3259, 'Technologie énergétique', 'Manufacturing', true),
  (883, 'Traitements des métaux', 'Manufacturing', true),
  (56, 'Exploitation minière', 'Oil, Gas, and Mining', true),
  (345, 'Extraction de minerais métalliques', 'Oil, Gas, and Mining', true),
  (356, 'Extraction de minerais non métalliques', 'Oil, Gas, and Mining', true),
  (332, 'Industries extractives', 'Oil, Gas, and Mining', true),
  (3238, 'Biotechnologie', 'Professional Services', true),
  (47, 'Comptabilité', 'Professional Services', true),
  (3213, 'Environnement et énergies renouvelables', 'Professional Services', true),
  (3221, 'Ingénierie mécanique ou industrielle', 'Professional Services', true),
  (3248, 'Ingénierie robotique', 'Professional Services', true),
  (3242, 'Services d''ingénierie', 'Professional Services', true),
  (86, 'Services de conseil en environnement', 'Professional Services', true),
  (11, 'Services et conseil aux entreprises', 'Professional Services', true),
  (3211, 'Biens et équipements pour les entreprises', 'Retail', true),
  (27, 'Commerce de détail', 'Retail', true),
  (1319, 'Commerce de détail d''appareils électriques et électroniques', 'Retail', true),
  (138, 'Commerce de détail de machines et d''équipements de bureau', 'Retail', true),
  (1324, 'Commerce de détail de matériaux de construction et matériel de jardinage', 'Retail', true),
  (1309, 'Commerce de détail de meubles et articles d''ameublement', 'Retail', true),
  (93, 'Entreposage et stockage', 'Transportation, Logistics, Supply Chain and Storage', true),
  (94, 'Transport aérien', 'Transportation, Logistics, Supply Chain and Storage', true),
  (95, 'Transport maritime', 'Transportation, Logistics, Supply Chain and Storage', true),
  (116, 'Transport, logistique, chaîne logistique et stockage', 'Transportation, Logistics, Supply Chain and Storage', true),
  (87, 'Transports de fret et de colis', 'Transportation, Logistics, Supply Chain and Storage', true),
  (92, 'Transports routiers de fret', 'Transportation, Logistics, Supply Chain and Storage', true),
  (398, 'Services de gestion des eaux, eaux usées, vapeur et climatisation', 'Utilities', true),
  (400, 'Traitement et distribution d''eau', 'Utilities', true),
  (1986, 'Traitement et élimination des déchets', 'Utilities', true),
  (133, 'Commerce de gros', 'Wholesale', true),
  (1187, 'Commerce de gros d''équipements industriels', 'Wholesale', true),
  (1267, 'Commerce de gros de boissons alcoolisées', 'Wholesale', true),
  (49, 'Commerce de gros de matériaux de construction', 'Wholesale', true),
  (1206, 'Commerce de gros de matériaux recyclables', 'Wholesale', true),
  (1171, 'Commerce de gros de matériel électrique et électronique', 'Wholesale', true),
  (1137, 'Commerce de gros de meubles et articles d''ameublement', 'Wholesale', true),
  (1212, 'Commerce de gros de papier et d''articles de papeterie', 'Wholesale', true),
  (134, 'Commerce de gros import-export', 'Wholesale', true),
  (3209, 'Import et export', 'Wholesale', true),
  (3197, 'Matériaux de construction', 'Wholesale', true)
ON CONFLICT (id) DO UPDATE SET label_fr = EXCLUDED.label_fr, parent_category = EXCLUDED.parent_category, verified = EXCLUDED.verified;

-- Geos: Pays prioritaires (insert countries first for parent_id refs)
INSERT INTO linkedin_geos (id, label_fr, geo_type) VALUES
  ('105015875', 'France', 'COUNTRY'),
  ('100565514', 'Belgique', 'COUNTRY'),
  ('106693272', 'Suisse', 'COUNTRY'),
  ('104042105', 'Luxembourg', 'COUNTRY'),
  ('101282230', 'Allemagne', 'COUNTRY'),
  ('105646813', 'Espagne', 'COUNTRY')
ON CONFLICT (id) DO NOTHING;

-- Geos: 13 Régions françaises
INSERT INTO linkedin_geos (id, label_fr, geo_type, parent_id) VALUES
  ('104246759', 'Île-de-France', 'REGION', '105015875'),
  ('103623254', 'Auvergne-Rhône-Alpes', 'REGION', '105015875'),
  ('102203735', 'Provence-Alpes-Côte d''Azur', 'REGION', '105015875'),
  ('105007536', 'Hauts-de-France', 'REGION', '105015875'),
  ('103876217', 'Occitanie', 'REGION', '105015875'),
  ('105563475', 'Nouvelle-Aquitaine', 'REGION', '105015875'),
  ('101735443', 'Grand Est', 'REGION', '105015875'),
  ('104731846', 'Pays de la Loire', 'REGION', '105015875'),
  ('104433326', 'Normandie', 'REGION', '105015875'),
  ('103737322', 'Bretagne', 'REGION', '105015875'),
  ('103286073', 'Bourgogne-Franche-Comté', 'REGION', '105015875'),
  ('102215960', 'Centre-Val de Loire', 'REGION', '105015875'),
  ('106926833', 'Corse', 'REGION', '105015875')
ON CONFLICT (id) DO NOTHING;

-- Geos: Grandes villes françaises
INSERT INTO linkedin_geos (id, label_fr, geo_type, parent_id) VALUES
  ('106383538', 'Paris', 'CITY', '104246759'),
  ('103815258', 'Lyon', 'CITY', '103623254'),
  ('103857854', 'Marseille', 'CITY', '102203735'),
  ('105073465', 'Toulouse', 'CITY', '103876217'),
  ('104787182', 'Bordeaux', 'CITY', '105563475'),
  ('100323840', 'Lille', 'CITY', '105007536'),
  ('105580607', 'Strasbourg', 'CITY', '101735443'),
  ('102565100', 'Nantes', 'CITY', '104731846'),
  ('106456329', 'Grenoble', 'CITY', '103623254'),
  ('105282085', 'Nice', 'CITY', '102203735'),
  ('104946573', 'Rennes', 'CITY', '103737322'),
  ('106719766', 'Montpellier', 'CITY', '103876217'),
  ('106834928', 'Metz', 'CITY', '101735443'),
  ('103264728', 'Clermont-Ferrand', 'CITY', '103623254'),
  ('106045821', 'Rouen', 'CITY', '104433326'),
  ('100853905', 'Dijon', 'CITY', '103286073')
ON CONFLICT (id) DO NOTHING;
